GET http://localhost:3000/enrollment

POST http://localhost:3000/enrollment
Content-Type: application/json
{
    "studentName": "Mustak Fuad",
    "courseId": "2"
}

POST http://localhost:3000/enrollment
Content-Type: application/json
{
    "studentName": "Pritik Kabir",
    "courseId": "3"
}

